name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 98.82.7.133
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "🚀 Starting Deployment..."

            PROJECT_DIR="/home/ubuntu/ci-cd-auto-rollback-project"

            echo "📂 Checking project directory..."

            # Clone or pull latest code
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "cloning repo..."
              git clone https://github.com/11-29/ci-cd-auto-rollback-project.git $PROJECT_DIR
            else
              echo "Repo exists, pulling latest..."
            fi

            cd $PROJECT_DIR

            echo "⬇️ Pulling latest code..."
            git pull

            echo "📦 Saving current version..."
            if docker ps -a --format '{{.Names}}' | grep -q "^my-app$"; then
              docker commit my-app my-app:latest
              echo "✅ Saved as stable version"
            else
              echo "⚠️ No running container found"
            fi
              
            echo "🔨 Building new image..."
            if ! docker build -t my-app:new .; then
              echo "❌ Build failed. Rolling back..."
              exit 1
            fi

            echo "🧪 Running new container on test port..."
            docker rm -f my-app-new || true

            if ! docker run -d -p 5001:5000 --name my-app-new my-app:new; then
              echo "❌ Container start failed. Rolling back..."
              docker rm -f my-app-new || true
              docker rm -f my-app || true
              docker run -d -p 5000:5000 --name my-app my-app:latest
              exit 1
            fi

            sleep 10

            echo "🔍 Running health check..."
            if curl -f http://localhost:5001/health; then
              echo "✅ App is healthy. Deploying to production..."

              # Remove old container
              docker rm -f my-app || true

              # Stop test container
              docker rm -f my-app-new || true

              # Run new container on production port
              docker run -d -p 5000:5000 --name my-app my-app:new

            else
              echo "❌ Health check failed. Rolling back..."

              docker rm -f my-app-new || true
              docker rm -f my-app || true

              docker run -d -p 5000:5000 --name my-app my-app:latest
              exit 1
            fi
          
            echo "🎉 Deployment Successful!"
