name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 32.193.4.42
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            script: |
  cd ci-cd-project

  git pull

  docker build -t my-app:new .

  docker tag my-app my-app:latest || true

  docker stop my-app || true
  docker rm my-app || true

  docker run -d -p 5000:5000 --name my-app-new my-app:new

  sleep 10

  if curl -f http://localhost:5000/health; then
    docker stop my-app-new
    docker rm my-app-new
    docker run -d -p 5000:5000 --name my-app my-app:new
  else
    docker stop my-app-new
    docker rm my-app-new
    docker run -d -p 5000:5000 --name my-app my-app:latest
  fi
